---
- hosts: webservers
  user: root
  vars:
    http_port: 80
    max_clients: 200
    custom_user: 'sumit'
    content: 'supermann'
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -f /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
    - setup: # aka gather_facts


  tasks:
    - name: Add new user
      user:
        name: '{{ custom_user }}'
        state: present
        shell: /bin/bash
        comment: 'create with ansible'
      become: true

    - name: Adding a file
      file:
        path: /tmp/foo.conf
        owner: '{{ custom_user }}'
        group: '{{ custom_user }}'
        state: file
        mode: 0644
      become: true

    - name: Adding new template file
      template:
        src: templates/templ.j2
        dest: /tmp/templated.conf
        owner: '{{ custom_user }}'
        group: '{{ custom_user }}'
        mode: 0600
      notify:
        reload sshd
      become: true

  handlers:
    - name: reload sshd
      action: service name=sshd state=reloaded
      become: true
