---
- hosts: webservers
  user: root
  vars:
    http_port: 80
    max_clients: 200
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -f /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
    - setup: # aka gather_facts


  tasks:
    - name: Adding a file
      file:
        path: /tmp/foo.conf
        owner: vagrant
        group: vagrant
        state: file
        mode: 0644

  handlers:
    - name: restart sshd
      action: service name=sshd state=restart
